// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1hEZu2DnNIEkfAs_mUEqBUgS-CECqWA',
    appId: '1:667791985478:web:911532cffa180ac0423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    authDomain: 'pushnotitutorial-75506.firebaseapp.com',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlud8jPJ6IEyuv2TRbNZbGjZ5a3mDiEH8',
    appId: '1:667791985478:android:890dd2c9ee27ecce423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOLO3gyn1-FdPIb-RHug4OqeoPZ3TwtE',
    appId: '1:667791985478:ios:060e5d4cdb122075423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
    iosBundleId: 'kz.tohawow.cleanarch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOLO3gyn1-FdPIb-RHug4OqeoPZ3TwtE',
    appId: '1:667791985478:ios:060e5d4cdb122075423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
    iosBundleId: 'kz.tohawow.cleanarch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1hEZu2DnNIEkfAs_mUEqBUgS-CECqWA',
    appId: '1:667791985478:web:8e2c186b01c88efb423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    authDomain: 'pushnotitutorial-75506.firebaseapp.com',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
    measurementId: 'G-SDW8H4KSTL',
  );

}